-- =====================================================
-- Admin Panel & Payment Flow - Database Schema
-- =====================================================
-- This migration creates the necessary tables and RLS policies
-- for tracking orders, payments, and link modifications.

-- =====================================================
-- 1. ORDERS TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  total_amount NUMERIC NOT NULL CHECK (total_amount >= 0),
  discount_code TEXT,
  discount_amount NUMERIC DEFAULT 0 CHECK (discount_amount >= 0),
  payment_method TEXT, -- 'wompi', 'stripe', etc
  payment_status TEXT DEFAULT 'pending' CHECK (payment_status IN ('pending', 'completed', 'failed', 'refunded')),
  payment_reference TEXT, -- External payment ID from gateway
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  completed_at TIMESTAMP WITH TIME ZONE
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_payment_status ON orders(payment_status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at DESC);

-- Enable RLS
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Users can view own orders" ON orders;
DROP POLICY IF EXISTS "Users can create orders" ON orders;
DROP POLICY IF EXISTS "Admins can view all orders" ON orders;

-- Users can view their own orders
CREATE POLICY "Users can view own orders"
  ON orders FOR SELECT
  USING (auth.uid() = user_id);

-- Only authenticated users can insert orders
CREATE POLICY "Users can create orders"
  ON orders FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Admins can view and manage all orders
CREATE POLICY "Admins can view all orders"
  ON orders FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role = 'admin'
    )
  );

-- =====================================================
-- 2. ORDER_ITEMS TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE NOT NULL,
  smart_link_id BIGINT REFERENCES smart_links(id) ON DELETE SET NULL,
  link_name TEXT NOT NULL,
  has_rotator BOOLEAN DEFAULT FALSE,
  price NUMERIC NOT NULL CHECK (price >= 0),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_smart_link_id ON order_items(smart_link_id);

-- Enable RLS
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Users can view own order items" ON order_items;
DROP POLICY IF EXISTS "Admins can view all order items" ON order_items;

-- Users can view items from their own orders
CREATE POLICY "Users can view own order items"
  ON order_items FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM orders
      WHERE orders.id = order_items.order_id
      AND orders.user_id = auth.uid()
    )
  );

-- Admins can view all order items
CREATE POLICY "Admins can view all order items"
  ON order_items FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role = 'admin'
    )
  );

-- =====================================================
-- 3. LINK_CHANGES TABLE (Audit Trail)
-- =====================================================
CREATE TABLE IF NOT EXISTS link_changes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  smart_link_id BIGINT REFERENCES smart_links(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  change_type TEXT NOT NULL CHECK (change_type IN (
    'design', 'button_add', 'button_remove', 'rotator_toggle', 
    'url_change', 'status_change', 'created', 'deleted'
  )),
  old_value JSONB,
  new_value JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_link_changes_smart_link_id ON link_changes(smart_link_id);
CREATE INDEX IF NOT EXISTS idx_link_changes_user_id ON link_changes(user_id);
CREATE INDEX IF NOT EXISTS idx_link_changes_created_at ON link_changes(created_at DESC);

-- Enable RLS
ALTER TABLE link_changes ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Users can view own link changes" ON link_changes;
DROP POLICY IF EXISTS "Authenticated users can log changes" ON link_changes;
DROP POLICY IF EXISTS "Admins can view all link changes" ON link_changes;

-- Users can view changes to their own links
CREATE POLICY "Users can view own link changes"
  ON link_changes FOR SELECT
  USING (user_id = auth.uid());

-- System can insert changes (authenticated users only)
CREATE POLICY "Authenticated users can log changes"
  ON link_changes FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Admins can view all changes
CREATE POLICY "Admins can view all link changes"
  ON link_changes FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role = 'admin'
    )
  );

-- =====================================================
-- 4. UPDATE SMART_LINKS TABLE
-- =====================================================
-- Add user_id column if it doesn't exist
DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'smart_links' AND column_name = 'user_id'
  ) THEN
    ALTER TABLE smart_links ADD COLUMN user_id UUID REFERENCES auth.users(id);
  END IF;
END $$;

-- Create index
CREATE INDEX IF NOT EXISTS idx_smart_links_user_id ON smart_links(user_id);

-- Enable RLS if not already enabled
ALTER TABLE smart_links ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Users can manage own links" ON smart_links;
DROP POLICY IF EXISTS "Admins can view all links" ON smart_links;

-- Users can view and edit their own links
CREATE POLICY "Users can manage own links"
  ON smart_links FOR ALL
  USING (user_id = auth.uid());

-- Admins can view all links
CREATE POLICY "Admins can view all links"
  ON smart_links FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role = 'admin'
    )
  );

-- =====================================================
-- 5. UPDATE TELEGRAM_BOTS TABLE
-- =====================================================
-- Enable RLS if not already enabled
ALTER TABLE telegram_bots ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Users can manage own telegram bots" ON telegram_bots;
DROP POLICY IF EXISTS "Admins can view all telegram bots" ON telegram_bots;

-- Users can manage bots for their own links
CREATE POLICY "Users can manage own telegram bots"
  ON telegram_bots FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM smart_links
      WHERE smart_links.id = telegram_bots.smart_link_id
      AND smart_links.user_id = auth.uid()
    )
  );

-- Admins can view all bots
CREATE POLICY "Admins can view all telegram bots"
  ON telegram_bots FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role = 'admin'
    )
  );

-- =====================================================
-- 6. HELPER FUNCTIONS
-- =====================================================

-- Function to automatically log link changes
CREATE OR REPLACE FUNCTION log_link_change()
RETURNS TRIGGER AS $$
BEGIN
  -- Only log if there's an actual change
  IF (TG_OP = 'UPDATE' AND OLD IS DISTINCT FROM NEW) OR TG_OP = 'INSERT' THEN
    INSERT INTO link_changes (
      smart_link_id,
      user_id,
      change_type,
      old_value,
      new_value
    ) VALUES (
      COALESCE(NEW.id, OLD.id),
      COALESCE(NEW.user_id, OLD.user_id),
      CASE 
        WHEN TG_OP = 'INSERT' THEN 'created'
        WHEN TG_OP = 'DELETE' THEN 'deleted'
        ELSE 'design'
      END,
      CASE WHEN TG_OP = 'DELETE' THEN row_to_json(OLD) ELSE row_to_json(OLD) END,
      CASE WHEN TG_OP = 'DELETE' THEN NULL ELSE row_to_json(NEW) END
    );
  END IF;
  
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create trigger for smart_links (optional - can be enabled later)
-- DROP TRIGGER IF EXISTS smart_links_change_log ON smart_links;
-- CREATE TRIGGER smart_links_change_log
--   AFTER INSERT OR UPDATE OR DELETE ON smart_links
--   FOR EACH ROW
--   EXECUTE FUNCTION log_link_change();

-- =====================================================
-- MIGRATION COMPLETE
-- =====================================================
-- Tables created:
--   - orders
--   - order_items
--   - link_changes
-- 
-- Updated tables:
--   - smart_links (added user_id, RLS policies)
--   - telegram_bots (RLS policies)
--
-- All tables have appropriate RLS policies to ensure:
--   - Users can only see their own data
--   - Admins can see all data
--   - Proper security and data isolation
